#!/usr/bin/env bash

echo "*******Create Bucket*******"

#check for the bucket name
if [ -z "$1" ]; then 
    echo "there need to be a bucket name provided eg. ./bucket my-buckrt-name"
    exit 1
fi

aws s3api create-bucket \
--bucket $1 \
--create-bucket-configuration="LocationConstraint='ap-south-1'" \
--query Location \
--output text